sudo: required

services:
  - docker

env:
  - COMPOSE_VERSION: 1.24.1
  - REPO_COMMIT_AUTHOR: $(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL: $(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE: $(git show -s --pretty=format:"%s")

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - ./travis-run.sh

notifications:
  email: vvzuuzqg@sharklasers.com