FORMAT: 1A
HOST: http://ic.x430n.com

# InstantCoach API

InstantCoach is an API making easy instant coaching between an Evaluator and an Agent through comments with attachments and bookmark pins to a recorded media.

## InstantCoach Collection [/api/instantcoach]

### List All InstantCoaches [GET /api/instantcoach{?skip}{?take}{?showCompleted}]

List of all InstantCoaches paginated, by default page is containing 10 items.
By default returns InstantCoaches that are not `Completed`, to show all Instant Coaches use `showCompleted` and set it to `true`.

+ Request Success

    + Parameters
        + skip: 0 (number, optional) -  Page number, starts with 0.
            + default: 0
        + take: 10 (number, optional) - Page row number, greater or equal 1.
            + default: 10
        + showCompleted: false (boolean, optional) - When true show all InstantCoaches, when false - default, shows all except those with status Completed.
            + default: false

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

+ Response 200 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "items": [
                {
                  "id": 1,
                  "status": "New",
                  "reference": "IC91749518577437",
                  "description": "IC no. 1",
                  "createdAt": "2019-07-19T23:15:52.2598622Z",
                  "updatedAt": "2019-07-19T23:15:52.2599463Z",
                  "commentsCount": 1,
                  "evaluatorName": "John Doe"
                },
                {
                  "id": 12,
                  "status": "InProgress",
                  "reference": "IC91670319134481",
                  "description": "IC no. 2",
                  "createdAt": "2019-07-19T21:03:52.3120829Z",
                  "updatedAt": "2019-07-21T19:58:26.126676Z",
                  "commentsCount": 10,
                  "evaluatorName": "John Doe"
                }
              ],
              "totalCount": 22
            }

+ Request No Data

    + Parameters
        + skip: 0 (number, optional) -  Page number, starts with 0.
            + default: 0
        + take: 10 (number, optional) - Page row number, greater or equal 1.
            + default: 10
        + showCompleted: false (boolean, optional) - When true show all InstantCoaches, when false - default, shows all except those with status Completed.
            + default: false

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

+ Response 200 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "items": [],
              "totalCount": 0
            }


### Create a new InstantCoach [POST]

Create a new InstantCoach using this action.
It takes a JSON object containing an InstantCoach properties,
collection of a comments (at least one required) and a bookmark pin(s) collection,
if referenced in a comments collection.

+ Request Success (application/json)

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

    + Body

            {
              "description": "InstantCoach no.1 description",
              "ticketId": "234567",
              "evaluatorId": 1,
              "agentId": 2,
              "evaluatorName": "John Doe",
              "agentName": "Jane Doe",
              "comments": [
                {
                  "commentType": "Bookmark",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:01:00.546Z",
                  "bookmarkPinId": 1
                },
                {
                  "commentType": "Attachment",
                  "text": "https://example.com/example.pdf",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:03:28.462Z"
                },
                {
                  "commentType": "Textual",
                  "text": "Some evaluator's comment",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:04:44.000Z"
                }
              ],
              "bookmarkPins": [
                {
                  "id": 1,
                  "index": 1,
                  "range": {
                    "start": 10,
                    "end": 32
                  },
                  "comment": "Some comment for pin",
                  "mediaUrl": "https://example.com/example.mp3"
                }
              ]
            }

    + Schema

            {
                "title": "Create InstantCoach",
                "description": "The client model for creating InstantCoach.",
                "type": "object",
                "properties": {
                    "description": {
                        "description": "The Description of InstantCoach. Required. Max length is 1000 characters.",
                        "type": "string",
                        "maxLength": 1000
                    },
                    "ticketId": {
                        "title": "Ticket Id",
                        "description": "The Id of Ticket for InstantCoach. Required. Should be representation of id int, long, GUID. Max length is 64 characters.",
                        "type": "string",
                        "maxLength": 64
                    },
                    "evaluatorId": {
                        "title": "Evaluator Id",
                        "description": "The Evaluator Id of InstantCoach. Required. Should be valid integer and greater than 1.",
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 2147483647
                    },
                    "agentId": {
                        "title": "Agent Id",
                        "description": "The Agent Id of InstantCoach. Required. Should be valid integer and greater than 1.",
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 2147483647
                    },
                    "evaluatorName": {
                        "title": "Evaluator Name",
                        "description": "The Evaluator name at time of creating InstantCoach. Required. Max length is 128 characters.",
                        "type": "string",
                        "maxLength": 128
                    },
                    "agentName": {
                        "title": "Agent Name",
                        "description": "The Agent name at time of creating InstantCoach. Required. Max length is 128 characters.",
                        "type": "string",
                        "maxLength": 128
                    },
                    "comments": {
                        "description": "The InstantCoach Comments. Required. Must be at least one comment.",
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/CommentClient"
                        }
                    },
                    "bookmarkPins": {
                        "title": "Bookmark Pins",
                        "description": "The Bookmark Pins used in Comments. Only if comment of type bookmark.",
                        "type": [
                            "array",
                            "null"
                        ],
                        "items": {
                            "$ref": "#/definitions/BookmarkPinClient"
                        }
                    }
                },
                "definitions": {
                    "BookmarkPinClient": {
                        "title": "InstantCoach Bookmark Pins",
                        "description": "The client model for InstantCoach bookmark pins.",
                        "type": [
                            "object",
                            "null"
                        ],
                        "properties": {
                            "id": {
                                "description": "The Id for Bookmark Pin. Used as reference in Comment of type 'Bookmark'. Required. Should be valid integer and greater than 1.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            },
                            "index": {
                                "description": "The index of bookmark pin, used to show pins in order. Required. Should be valid integer and greater than 1.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            },
                            "range": {
                                "$ref": "#/definitions/RangeClient"
                            },
                            "comment": {
                                "description": "The comment about Bookmark Pin. Max length is 1000 characters.",
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "maxLength": 1000
                            },
                            "mediaUrl": {
                                "description": "The Bookmark pin media url.",
                                "type": "string",
                                "maxLength": 1000
                            }
                        },
                        "required": [
                            "id",
                            "index",
                            "range",
                            "mediaUrl"
                        ]
                    },
                    "CommentClient": {
                        "title": "InstantCoach Comments",
                        "description": "The client model for InstantCoach comments.",
                        "type": [
                            "object",
                            "null"
                        ],
                        "properties": {
                            "commentType": {
                                "title": "Comment Type",
                                "description": "The type of Comment, can be 'Textual', 'Attachment' and 'Bookmark'. Required.",
                                "type": "string",
                                "enum": [
                                    "Textual",
                                    "Bookmark",
                                    "Attachment"
                                ]
                            },
                            "text": {
                                "description": "The Comment text, required for 'Textual' and 'Attachment' type. Max length is 1000 characters.",
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "maxLength": 1000
                            },
                            "authorType": {
                                "title": "Author Type",
                                "description": "The comment author, can be either 'Evaluator' or 'Agent'. Required.",
                                "type": "string",
                                "enum": [
                                    "Evaluator",
                                    "Agent"
                                ]
                            },
                            "createdAt": {
                                "title": "Created At",
                                "description": "The date and time when Comment is created. Used for chronological view of comments. Required.",
                                "type": "string",
                                "format": "date-time"
                            },
                            "bookmarkPinId": {
                                "title": "Bookmark Pin Id",
                                "description": "The bookmark pin id for Comment. Null by default, but required when comment type is 'Bookmark'.",
                                "type": [
                                    "integer",
                                    "null"
                                ]
                            }
                        },
                        "required": [
                            "commentType",
                            "authorType",
                            "createdAt"
                        ]
                    },
                    "RangeClient": {
                        "title": "Bookmark Pin Range",
                        "description": "The range of pin with starting and ending point in seconds. Required.",
                        "type": [
                            "object",
                            "null"
                        ],
                        "properties": {
                            "start": {
                                "description": "Pin starting point in seconds. Required. Must be greater than 1.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            },
                            "end": {
                                "description": "Pin ending point in seconds. Required. Must be greater than 1 and greater than starting point.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            }
                        },
                        "required": [
                            "start",
                            "end"
                        ]
                    }
                },
                "required": [
                    "description",
                    "ticketId",
                    "evaluatorId",
                    "agentId",
                    "evaluatorName",
                    "agentName",
                    "comments"
                ]
            }


+ Response 201 (application/json)

    + Headers

            Location: api/instantcoaches/1
            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "id": 1
            }

+ Request Bad Request (application/json)

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

    + Body

            {
              "description": "string",
              "ticketId": "string",
              "evaluatorId": 0,
              "agentId": 0,
              "evaluatorName": "string",
              "agentName": "string",
              "comments": [
                {
                  "commentType": "Textual",
                  "text": "string",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T21:15:34.816Z",
                  "bookmarkPinId": 0
                }
              ],
              "bookmarkPins": [
                {
                  "id": 0,
                  "index": 0,
                  "range": {
                    "start": 0,
                    "end": 0
                  },
                  "mediaUrl": "string"
                }
              ]
            }


+ Response 400 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "isValid": false,
              "errors": {
                "AgentId": [
                  "The field Agent Id must be between 1 and 2147483647."
                ],
                "EvaluatorId": [
                  "The field Evaluator Id must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Id": [
                  "The field Id must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Index": [
                  "The field Index must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Range.End": [
                  "The field End must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Range.Start": [
                  "The field Start must be between 1 and 2147483647."
                ]
              }
            }


### Get existing InstantCoach [GET /api/instantcoaches/{id}]

Get existing data for wanted InstantCoach using this action.

+ Request Success

    + Parameters
        + id: 1 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ


+ Response 200 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "id": 1032,
              "ticketId": "234567",
              "description": "InstantCoach no.1 description",
              "evaluatorName": "John Doe",
              "comments": [
                {
                  "commentType": "Bookmark",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:01:00.546Z",
                  "bookmarkPinId": 1
                },
                {
                  "commentType": "Attachment",
                  "text": "https://example.com/example.pdf",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:03:28.462Z"
                },
                {
                  "commentType": "Textual",
                  "text": "Some evaluator's comment",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:04:44Z"
                },
                {
                  "commentType": "Textual",
                  "text": "Agent's reply to Evaluator's comment",
                  "authorType": "Agent",
                  "createdAt": "2019-07-22T20:04:44Z"
                }
              ],
              "bookmarkPins": [
                {
                  "id": 1,
                  "index": 1,
                  "range": {
                    "start": 10,
                    "end": 32
                  },
                  "mediaUrl": "https://example.com/example.mp3"
                }
              ]
            }


+ Request Not Found

    + Parameters
        + id: 12 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ\


+ Response 404 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "message": "Not existing id: 12"
            }


### Update an existing InstantCoach [PUT /api/instantcoaches/{id}]

Update an existing InstantCoach using this action.
It takes a JSON object containing an _Update Type_ (`Save` or `Review`),
collection of a comments (at least one required) and a bookmark pin(s) collection,
if referenced in a comments collection.

+ Request Success (application/json)

    + Parameters
        + id: 1 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

    + Body

            {
              "updateType": "Save",
              "comments": [
                {
                  "commentType": "Bookmark",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:01:00.546Z",
                  "bookmarkPinId": 1
                },
                {
                  "commentType": "Attachment",
                  "text": "https://example.com/example.pdf",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:03:28.462Z"
                },
                {
                  "commentType": "Textual",
                  "text": "Some evaluator's comment",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T20:04:44.000Z"
                },
                {
                  "commentType": "Textual",
                  "text": "Agent's reply to Evaluator's comment",
                  "authorType": "Agent",
                  "createdAt": "2019-07-22T20:04:44.000Z"
                }
              ],
              "bookmarkPins": [
                {
                  "id": 1,
                  "index": 1,
                  "range": {
                    "start": 10,
                    "end": 32
                  },
                  "comment": "Some comment for pin",
                  "mediaUrl": "https://example.com/example.mp3"
                }
              ]
            }

    + Schema

            {
                "title": "Update InstantCoach",
                "description": "The client model for update InstantCoach.",
                "type": "object",
                "properties": {
                    "updateType": {
                        "title": "Update Type",
                        "description": "The type of InstantCoach Update, can be of 'Save' or 'Review'. When 'Save' then InstantCoach Status is set to 'In Progress', on 'Review' type is set to be 'Waiting'.",
                        "type": "string",
                        "enum": [
                            "Save",
                            "Review"
                        ]
                    },
                    "comments": {
                        "description": "The InstantCoach Comments. Required. Must be at least one comment.",
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/CommentClient"
                        }
                    },
                    "bookmarkPins": {
                        "title": "Bookmark Pins",
                        "description": "The Bookmark Pins used in Comments. Only if comment of type bookmark.",
                        "type": [
                            "array",
                            "null"
                        ],
                        "items": {
                            "$ref": "#/definitions/BookmarkPinClient"
                        }
                    }
                },
                "definitions": {
                    "BookmarkPinClient": {
                        "title": "InstantCoach Bookmark Pins",
                        "description": "The client model for InstantCoach bookmark pins.",
                        "type": [
                            "object",
                            "null"
                        ],
                        "properties": {
                            "id": {
                                "description": "The Id for Bookmark Pin. Used as reference in Comment of type 'Bookmark'. Required. Should be valid integer and greater than 1.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            },
                            "index": {
                                "description": "The index of bookmark pin, used to show pins in order. Required. Should be valid integer and greater than 1.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            },
                            "range": {
                                "$ref": "#/definitions/RangeClient"
                            },
                            "comment": {
                                "description": "The comment about Bookmark Pin. Max length is 1000 characters.",
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "maxLength": 1000
                            },
                            "mediaUrl": {
                                "description": "The Bookmark pin media url.",
                                "type": "string",
                                "maxLength": 1000
                            }
                        },
                        "required": [
                            "id",
                            "index",
                            "range",
                            "mediaUrl"
                        ]
                    },
                    "CommentClient": {
                        "title": "InstantCoach Comments",
                        "description": "The client model for InstantCoach comments.",
                        "type": [
                            "object",
                            "null"
                        ],
                        "properties": {
                            "commentType": {
                                "title": "Comment Type",
                                "description": "The type of Comment, can be 'Textual', 'Attachment' and 'Bookmark'. Required.",
                                "type": "string",
                                "enum": [
                                    "Textual",
                                    "Bookmark",
                                    "Attachment"
                                ]
                            },
                            "text": {
                                "description": "The Comment text, required for 'Textual' and 'Attachment' type. Max length is 1000 characters.",
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "maxLength": 1000
                            },
                            "authorType": {
                                "title": "Author Type",
                                "description": "The comment author, can be either 'Evaluator' or 'Agent'. Required.",
                                "type": "string",
                                "enum": [
                                    "Evaluator",
                                    "Agent"
                                ]
                            },
                            "createdAt": {
                                "title": "Created At",
                                "description": "The date and time when Comment is created. Used for chronological view of comments. Required.",
                                "type": "string",
                                "format": "date-time"
                            },
                            "bookmarkPinId": {
                                "title": "Bookmark Pin Id",
                                "description": "The bookmark pin id for Comment. Null by default, but required when comment type is 'Bookmark'.",
                                "type": [
                                    "integer",
                                    "null"
                                ]
                            }
                        },
                        "required": [
                            "commentType",
                            "authorType",
                            "createdAt"
                        ]
                    },
                    "RangeClient": {
                        "title": "Bookmark Pin Range",
                        "description": "The range of pin with starting and ending point in seconds. Required.",
                        "type": [
                            "object",
                            "null"
                        ],
                        "properties": {
                            "start": {
                                "description": "Pin starting point in seconds. Required. Must be greater than 1.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            },
                            "end": {
                                "description": "Pin ending point in seconds. Required. Must be greater than 1 and greater than starting point.",
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 2147483647
                            }
                        },
                        "required": [
                            "start",
                            "end"
                        ]
                    }
                },
                "required": [
                    "updateType",
                    "comments"
                ]
            }


+ Response 204

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms


+ Request Not Found (application/json)

    + Parameters
        + id: 12 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

    + Body

            {
              "updateType": "Save",
              "comments": [
                {
                  "commentType": "Textual",
                  "text": "string",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T21:23:51.117Z",
                  "bookmarkPinId": 0
                }
              ]
            }


+ Response 404 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "message": "Not existing id: 12"
            }



+ Request Bad Request (application/json)

    + Parameters
        + id: 1 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ

    + Body

            {
              "updateType": "Save",
              "comments": [
                {
                  "commentType": "Textual",
                  "text": "string",
                  "authorType": "Evaluator",
                  "createdAt": "2019-07-21T21:23:51.117Z",
                  "bookmarkPinId": 0
                }
              ],
              "bookmarkPins": [
                {
                  "id": 0,
                  "index": 0,
                  "range": {
                    "start": 0,
                    "end": 0
                  },
                  "comment": "string",
                  "mediaUrl": "string"
                }
              ]
            }


+ Response 400 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "isValid": false,
              "errors": {
                "BookmarkPins[0].Id": [
                  "The field Id must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Index": [
                  "The field Index must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Range.End": [
                  "The field End must be between 1 and 2147483647."
                ],
                "BookmarkPins[0].Range.Start": [
                  "The field Start must be between 1 and 2147483647."
                ]
              }
            }


### Make an InstantCoach Completed [PATCH /api/instantcoaches/{id}/completed]

Make an existing InstantCoach completed using this action.

+ Request Success

    + Parameters
        + id: 1 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ


+ Response 204

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms


+ Request Not Found

    + Parameters
        + id: 12 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ


+ Response 404 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "message": "Not existing id: 12"
            }

### Delete an existing InstantCoach [DELETE /api/instantcoaches/{id}]

Delete an existing InstantCoach using this action.

+ Request Success

    + Parameters
        + id: 1 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ


+ Response 204

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms


+ Request Not Found

    + Parameters
        + id: 12 (number, required) - Id of an InstantCoch, greater than zero.

    + Headers

            X-Api-Version: 2.0
            Authorization: Bearer eyJ0eFNGx7...L8UtEJQ


+ Response 404 (application/json)

    + Headers

            Api-Supported-Versions: 1.0, 2.0
            X-Response-Time: 24ms

    + Body

            {
              "message": "Not existing id: 12"
            }