version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-GDR-ubuntu
    environment:
      SA_PASSWORD: "Abc$$12345"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"

  api:
    #image: x430n/ic-api:latest
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - DB_HOST=db
      - DB_NAME=test
      - DB_USER=sa
      - DB_PASSWORD="Abc$$12345"
      - JWT_AUTHORITY=https://dev-ajj38rm9.auth0.com
      - JWT_AUDIENCE=https://ic.x430n.com
      - ELASTIC_APM_SERVER_URLS=http://apm:8200
      - ELASTIC_APM_SERVICE_NAME=InstantCoach API
      - ELASTIC_APM_METRICS_INTERVAL="30s"
    ports:
        - "5000:5000"
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  proxy:
    #image: x430n/ic-nginx:latest
    build:
      context:  ./_nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "453:453"
    links:
      - api
    depends_on:
      - api

  # APM stack
  elasticsearch:
    build:
      context: ./_apm/elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=apm-ic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: kibana:6.8.1
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601

  apm:
    build:
      context: ./_apm/apm-server
      dockerfile: Dockerfile
      args:
        - APM_ENV=Test
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana