version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-GDR-ubuntu
    environment:
      SA_PASSWORD: "Abc$$12345"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  api:
    #image: x430n/ic-api:latest
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - DB_HOST=db
      - DB_NAME=test
      - DB_USER=sa
      - DB_PASSWORD="Abc$$12345"
      - JWT_AUTHORITY=https://dev-ajj38rm9.auth0.com
      - JWT_AUDIENCE=http://10.5.0.3
    ports:
        - "5000:5000"
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  proxy:
    #image: x430n/ic-nginx:latest
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "453:453"
    links:
      - api
    depends_on:
      - api
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16