version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-GDR-ubuntu
    environment:
      SA_PASSWORD: "Abc$$12345"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - ASPNETCORE_HTTPS_PORT=5001
      - DB_HOST=10.5.0.2
      - DB_NAME=test
      - DB_USER=sa
      - DB_PASSWORD="Abc$$12345"
      - JWT_AUTHORITY=https://dev-ajj38rm9.auth0.com
      - JWT_AUDIENCE=https://10.5.0.3
      - ASPNETCORE_Kestrel__Certificates__Default__Password=bm8kpv@=n2y4Nz@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/instant-coach-api.pfx
    ports:
        - "5000:80"
        - "5001:443"
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16