version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Abc$$12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  app:
    build: .
    ports:
        - "5000:5000"
    depends_on:
      - db