version: '3'

# If only APM needed to be started and hardcoded in api project apm server url
services:
  kibana:
    image: kibana:6.8.1
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=apm-ic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  apm:
    build:
      context: apm-server
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana
