version: '3'

# If only APM needed to be started and hard-coded in api project apm server url
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    # build:
    #   context: ./_apm/elasticsearch
    #   dockerfile: Dockerfile
    environment:
    # - cluster.name=apm-ic
    # - network.host=0.0.0.0
    - discovery.type=single-node
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      #- 9300:9300

  kibana:
    image: kibana:7.2.0
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - XPACK_MONITORING_ENABLED=true
    links:
      - elasticsearch
    ports:
      - 5601:5601

  apm:
    build:
      context: apm-server
      dockerfile: Dockerfile
      args:
        - APM_ENV=Dev
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana
    depends:
      - elasticsearch
      - kibana
