version: '3'

# If only APM needed to be started and hard-coded in api project apm server url
services:
  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=apm-ic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.2.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601

  apm:
    build:
      context: apm-server
      dockerfile: Dockerfile
      args:
        - APM_ENV=Dev
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana
    depends:
      - elasticsearch
      - kibana
