version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-GDR-ubuntu
    environment:
      SA_PASSWORD: "Abc$$12345"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"

  api:
    #image: x430n/ic-api:latest
    build:
      context:  ../
      dockerfile: docker/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - DB_HOST=db
      - DB_NAME=test
      - DB_USER=sa
      - DB_PASSWORD="Abc$$12345"
      - JWT_AUTHORITY=https://dev-ajj38rm9.auth0.com
      - JWT_AUDIENCE=https://ic.x430n.com
      - ELASTIC_APM_SERVER_URLS=http://apm:8200
      - ELASTIC_APM_SERVICE_NAME=InstantCoach API
      - ELASTIC_APM_METRICS_INTERVAL="30s"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
        - "5000:5000"
    depends_on:
      - db

  proxy:
    #image: x430n/ic-nginx:latest
    build:
      context:  nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "453:453"
    links:
      - api
    depends_on:
      - api

  # APM stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    # build:
    #   context: ./_apm/elasticsearch
    #   dockerfile: Dockerfile
    environment:
    # - cluster.name=apm-ic
    # - network.host=0.0.0.0
    - discovery.type=single-node
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      #- 9300:9300

  kibana:
    image: kibana:7.2.0
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - XPACK_MONITORING_ENABLED=true
    links:
      - elasticsearch
    ports:
      - 5601:5601

  apm:
    build:
      context: apm/apm-server
      dockerfile: Dockerfile
      args:
        - APM_ENV=Test
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana