version: "3.7"
services:
  db.ci:
    image: mcr.microsoft.com/mssql/server:2017-GDR-ubuntu
    environment:
      SA_PASSWORD: "Abc$$12345"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"

  api.ci:
    #image: x430n/ic-api:latest
    build:
      context:  ../../
      dockerfile: docker/ci/Dockerfile
      # args:
      #   - TRAVIS_BRANCH
      #   - TRAVIS_COMMIT
      #   - TRAVIS_JOB_ID
      #   - REPO_COMMIT_AUTHOR
      #   - REPO_COMMIT_AUTHOR_EMAIL
      #   - REPO_COMMIT_MESSAGE
    environment:
      - ASPNETCORE_ENVIRONMENT=SUT
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - DB_HOST=db.ci
      - DB_NAME=test
      - DB_USER=sa
      - DB_PASSWORD="Abc$$12345"
      - JWT_AUTHORITY=https://dev-ajj38rm9.auth0.com
      - JWT_AUDIENCE=https://ic.x430n.com
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
      - REPO_COMMIT_AUTHOR=${REPO_COMMIT_AUTHOR}
      - REPO_COMMIT_AUTHOR_EMAIL=${REPO_COMMIT_AUTHOR_EMAIL}
      - REPO_COMMIT_MESSAGE="${REPO_COMMIT_MESSAGE}"
    ports:
        - "5000:5000"
    depends_on:
      - db.ci